/**
 * Plan catalogue — the single source of truth for what each plan costs and
 * what it allows.
 *
 * The marketing site (separate repo) publishes these numbers from its own i18n
 * files. They must agree. `pnpm --filter @anis/types test` checks the shape;
 * agreement with the marketing copy is checked by hand at release, because the
 * two repos deploy independently.
 *
 * Marketing-site parity source:
 *   D:\Work\Projects\anis-chat\src\i18n\en.ts  →  `pricing.tiers`
 *
 * Rules that come from the product brief and must not be quietly broken:
 *   - Every plan has a finite AI-reply allowance. There is no unlimited plan.
 *   - Overage is billed at a published rate, and every account has a hard
 *     spending cap that stops replies rather than running up a bill.
 *   - WhatsApp / Meta messaging fees are passed through, never bundled.
 */

/* -------------------------------------------------------------------------
 * Plan identity
 * ---------------------------------------------------------------------- */

export const PLAN_IDS = ['free', 'starter', 'growth', 'pro', 'agency'] as const;

export type PlanId = (typeof PLAN_IDS)[number];

/**
 * Capability flags. Checked at the API boundary, never only in the UI —
 * hiding a button is not enforcement.
 */
export const PLAN_FEATURES = [
  /** Remove the "Powered by Anis" badge from the widget. */
  'removeBranding',
  'basicAnalytics',
  'advancedAnalytics',
  'leadCapture',
  'emailEscalation',
  /** A human can take the conversation over; the AI stops answering. */
  'humanTakeover',
  /** Surface questions the knowledge base could not answer. */
  'knowledgeGaps',
  /** Re-crawl website sources on a schedule. */
  'autoSourceRefresh',
  'multipleMembers',
  'apiAccess',
  /** Booking / lead / order-lookup actions. Gated until genuinely implemented. */
  'advancedActions',
  'prioritySupport',
  /** Agency: manage client workspaces from one dashboard. */
  'clientWorkspaces',
  'whiteLabel',
  'clientInvitations',
  'brandedReports',
  'workspaceDuplication',
] as const;

export type PlanFeature = (typeof PLAN_FEATURES)[number];

/**
 * Features that are sold on a plan but NOT yet built.
 *
 * The brief's golden rule: never advertise a capability before it ships. These
 * are listed on the pricing page with a "when available" qualifier, and the
 * product must refuse to enable them rather than half-working. Delete an entry
 * here the day the feature is real — and only then.
 */
export const NOT_YET_SHIPPED: readonly PlanFeature[] = ['advancedActions'] as const;

/* -------------------------------------------------------------------------
 * Plan shape
 * ---------------------------------------------------------------------- */

export interface PlanLimits {
  /**
   * AI replies included per billing period. An "AI reply" is one assistant
   * message generated by the model — not a conversation, and not a message
   * sent by a human agent during takeover.
   */
  aiRepliesPerMonth: number;
  /** Workspaces (= assistants). Agencies get many; everyone else gets one. */
  workspaces: number;
  /** Distinct websites that may be crawled as sources, across the account. */
  websites: number;
  /** Team members with dashboard access, including the owner. */
  members: number;
  /** Knowledge sources per workspace (pages, PDFs, text blocks, FAQ sets). */
  sourcesPerWorkspace: number;
  /** Ceiling on total indexed chunks per workspace — the real cost driver. */
  chunksPerWorkspace: number;
  /**
   * Pages fetched in one website crawl. Separate from sourcesPerWorkspace
   * because a single site can be thousands of pages, and each one costs an
   * outbound request against the customer's own server as well as embedding
   * spend.
   */
  pagesPerCrawl: number;
  /**
   * Conversation retention, in days. `null` means "keep until deleted", which
   * we only offer where the customer has configured it deliberately — the
   * privacy page states the actual number.
   */
  retentionDays: number | null;
}

export interface Plan {
  id: PlanId;
  /** Display name. Not translated — the plan names are the same in AR and EN. */
  name: string;
  /** USD per month, billed monthly. */
  monthlyUsd: number;
  /**
   * USD per month when billed annually. The marketing site advertises
   * "2 months free", i.e. an annual bill of 10 × the monthly price.
   */
  annualMonthlyUsd: number;
  limits: PlanLimits;
  features: readonly PlanFeature[];
  /** Highlighted as "Most popular" on the pricing page. */
  popular?: boolean;
}

/** Annual billing charges 10 months for 12 — the "2 months free" claim. */
export const ANNUAL_MONTHS_CHARGED = 10;

const annual = (monthly: number): number =>
  Math.round(((monthly * ANNUAL_MONTHS_CHARGED) / 12) * 100) / 100;

/* -------------------------------------------------------------------------
 * The catalogue
 * ---------------------------------------------------------------------- */

export const PLANS: Record<PlanId, Plan> = {
  free: {
    id: 'free',
    name: 'Free',
    monthlyUsd: 0,
    annualMonthlyUsd: 0,
    limits: {
      aiRepliesPerMonth: 50,
      workspaces: 1,
      websites: 1,
      members: 1,
      sourcesPerWorkspace: 5,
      chunksPerWorkspace: 500,
      pagesPerCrawl: 20,
      retentionDays: 30,
    },
    features: [],
  },

  starter: {
    id: 'starter',
    name: 'Starter',
    monthlyUsd: 29,
    annualMonthlyUsd: annual(29),
    limits: {
      aiRepliesPerMonth: 1_000,
      workspaces: 1,
      websites: 1,
      // Just the owner: inviting people starts at Growth (`multipleMembers`).
      members: 1,
      sourcesPerWorkspace: 50,
      chunksPerWorkspace: 10_000,
      pagesPerCrawl: 100,
      retentionDays: 90,
    },
    features: ['basicAnalytics', 'leadCapture', 'emailEscalation'],
  },

  growth: {
    id: 'growth',
    name: 'Growth',
    monthlyUsd: 79,
    annualMonthlyUsd: annual(79),
    popular: true,
    limits: {
      aiRepliesPerMonth: 4_000,
      workspaces: 1,
      websites: 3,
      members: 5,
      sourcesPerWorkspace: 200,
      chunksPerWorkspace: 50_000,
      pagesPerCrawl: 300,
      retentionDays: 180,
    },
    features: [
      'basicAnalytics',
      'advancedAnalytics',
      'leadCapture',
      'emailEscalation',
      'removeBranding',
      'knowledgeGaps',
      'humanTakeover',
      'autoSourceRefresh',
      'multipleMembers',
    ],
  },

  pro: {
    id: 'pro',
    name: 'Pro',
    monthlyUsd: 149,
    annualMonthlyUsd: annual(149),
    limits: {
      aiRepliesPerMonth: 10_000,
      workspaces: 3,
      websites: 10,
      members: 15,
      sourcesPerWorkspace: 1_000,
      chunksPerWorkspace: 200_000,
      pagesPerCrawl: 1_000,
      retentionDays: 365,
    },
    features: [
      'basicAnalytics',
      'advancedAnalytics',
      'leadCapture',
      'emailEscalation',
      'removeBranding',
      'knowledgeGaps',
      'humanTakeover',
      'autoSourceRefresh',
      'multipleMembers',
      'apiAccess',
      'advancedActions',
      'prioritySupport',
    ],
  },

  agency: {
    id: 'agency',
    name: 'Agency',
    monthlyUsd: 299,
    annualMonthlyUsd: annual(299),
    limits: {
      /** Shared across every client workspace on the account. */
      aiRepliesPerMonth: 25_000,
      workspaces: 20,
      websites: 20,
      members: 25,
      sourcesPerWorkspace: 1_000,
      chunksPerWorkspace: 200_000,
      pagesPerCrawl: 1_000,
      retentionDays: 365,
    },
    features: [
      'basicAnalytics',
      'advancedAnalytics',
      'leadCapture',
      'emailEscalation',
      'removeBranding',
      'knowledgeGaps',
      'humanTakeover',
      'autoSourceRefresh',
      'multipleMembers',
      'apiAccess',
      'advancedActions',
      'prioritySupport',
      'clientWorkspaces',
      'whiteLabel',
      'clientInvitations',
      'brandedReports',
      'workspaceDuplication',
    ],
  },
};

export const PLAN_LIST: readonly Plan[] = PLAN_IDS.map((id) => PLANS[id]);

/* -------------------------------------------------------------------------
 * Add-ons, overage, spending caps
 * ---------------------------------------------------------------------- */

export const ADDONS = {
  /**
   * An extra agency client workspace, beyond the 20 included. Brief says
   * $10–15/mo plus usage; we bill the low end and let usage do the rest.
   */
  extraWorkspaceUsd: 12,
} as const;

/**
 * Price per AI reply once the plan allowance is exhausted, in USD.
 *
 * Deliberately above marginal model cost — an overage reply also carries
 * retrieval, storage and support cost. Confirm against measured per-reply cost
 * before launch; the brief requires each plan to be profitable against real
 * model, hosting, storage and channel costs.
 */
export const OVERAGE_USD_PER_REPLY = 0.02;

/**
 * Credit top-up bundles. Credits never expire and are consumed only after the
 * plan allowance is used up.
 */
export const CREDIT_PACKS = [
  { replies: 1_000, usd: 15 },
  { replies: 5_000, usd: 60 },
  { replies: 20_000, usd: 200 },
] as const;

/**
 * Default hard spending cap, in USD of overage per period.
 *
 * This is a stop, not a warning: when overage spend reaches the cap the
 * assistant stops generating AI replies and falls back to collecting the
 * visitor's contact details for a human. Every account has one; the owner can
 * raise it, and setting it to 0 disables overage entirely.
 */
export const DEFAULT_HARD_CAP_USD = 50;

/** Fractions of the allowance at which the account owner is emailed. */
export const USAGE_WARNING_THRESHOLDS = [0.8, 1.0] as const;

/* -------------------------------------------------------------------------
 * Queries
 * ---------------------------------------------------------------------- */

export function planHasFeature(plan: PlanId, feature: PlanFeature): boolean {
  return PLANS[plan].features.includes(feature);
}

/**
 * Whether a feature can actually be used right now: it must be both sold on
 * the plan AND built. Call this — not `planHasFeature` — at the point of use,
 * so an unshipped capability cannot be switched on by an entitlement alone.
 */
export function featureIsAvailable(plan: PlanId, feature: PlanFeature): boolean {
  return planHasFeature(plan, feature) && !NOT_YET_SHIPPED.includes(feature);
}

export function planLimit<K extends keyof PlanLimits>(plan: PlanId, limit: K): PlanLimits[K] {
  return PLANS[plan].limits[limit];
}

/** USD charged for `n` replies beyond the plan allowance. */
export function overageCostUsd(repliesOverAllowance: number): number {
  if (repliesOverAllowance <= 0) return 0;
  return Math.round(repliesOverAllowance * OVERAGE_USD_PER_REPLY * 100) / 100;
}

/**
 * How many overage replies an account may still generate before its hard cap
 * stops it. Returns 0 when the cap is reached — callers must then refuse to
 * generate and offer human handoff instead.
 */
export function repliesRemainingUnderCap(overageSpentUsd: number, hardCapUsd: number): number {
  const budget = hardCapUsd - overageSpentUsd;
  if (budget <= 0) return 0;
  return Math.floor(budget / OVERAGE_USD_PER_REPLY);
}

/** Total USD billed for a full year on the annual plan. */
export function annualTotalUsd(plan: PlanId): number {
  return PLANS[plan].monthlyUsd * ANNUAL_MONTHS_CHARGED;
}
